### PR TITLE
fix for adjoints with preequilibration and sensitivities

### LINKED ISSUE #333: Incorrect sensitivities when using preequilibration with adjoint sensitivities
When using preequilibration with adjoint sensitivities `sx0` is (silently) not set. This leads to wrong `sllh`.

### PR DESCRIPTION
**Pull request by paulstapor**
fix #333

### CODE REVIEW

**Comment by paulstapor** [comment]
That should already do the job... so let's not wait until Friday, if this is enough

File: src/steadystateproblem.cpp [hunk 1]
```diff
@@ -70,8 +70,7 @@ void SteadystateProblem::workSteadyStateProblem(ReturnData *rdata,
     getNewtonOutput(rdata, model, newton_status, run_time, it);
 
     /* Compute steady state sensitvities */
-    if (rdata->sensi_meth == AMICI_SENSI_FSA &&
-        rdata->sensi >= AMICI_SENSI_ORDER_FIRST)
+    if (rdata->sensi >= AMICI_SENSI_ORDER_FIRST)
```
Comment (dweindl) [inline src/steadystateproblem.cpp]: && rdata->sensimeth != AMICI_SENSI_NONE

**Comment by paulstapor** [comment]
Just for the moment, I added the other solver which can also be used for preequilibration and changed the naming in the way we discussed...
I hope things are ready for merging now...
