### PR TITLE
fix(CI) ignore multiple @param sections warning for the time being, fixes #504

### LINKED ISSUE #504: Fix run-doxygen.sh matlab documentation errors
```
DOXYGEN failed:

/Users/travis/build/ICB-DCM/AMICI/matlab/SBML2AMICI.m:17: warning: argument 'modelname' from the argument list of SBML2AMICI has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amifun/amifun.m:131: warning: argument 'fid' from the argument list of amifun::writeCcode_sensi has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amifun/amifun.m:133: warning: argument 'fid' from the argument list of amifun::writeCcode has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amifun/amifun.m:135: warning: argument 'model' from the argument list of amifun::writeMcode has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amifun/amifun.m:149: warning: argument 'model' from the argument list of amifun::getSyms has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:612: warning: argument 'xdot' from the argument list of amimodel::updateRHS has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:627: warning: argument 'modelname' from the argument list of amimodel::updateModelName has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:640: warning: argument 'wrap_path' from the argument list of amimodel::updateWrapPath has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:659: warning: argument 'amimodelo2' from the argument list of amimodel::generateM has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:661: warning: argument 'funstr' from the argument list of amimodel::getFun has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:678: warning: argument 'cfun' from the argument list of amimodel::compileAndLinkModel has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/matlab/@amimodel/amimodel.m:680: warning: argument 'adjoint' from the argument list of amimodel::generateMatlabWrapper has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'layout' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'TransA' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'M' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'N' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'alpha' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'A' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'lda' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'X' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'incX' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'beta' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'Y' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:8: warning: argument 'incY' from the argument list of amici::amici_dgemv has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'layout' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'TransA' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'TransB' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'M' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'N' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'K' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'alpha' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'A' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'lda' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'B' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'ldb' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'beta' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'C' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/cblas.h:13: warning: argument 'ldc' from the argument list of amici::amici_dgemm has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/interface_matlab.h:46: warning: argument 'prhs' from the argument list of amici::expDataFromMatlabCall has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:12: warning: argument 'rdata' from the argument list of amici::getReturnDataMatlabFromAmiciCall has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:13: warning: argument 'rdata' from the argument list of amici::initMatlabReturnFields has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:14: warning: argument 'rdata' from the argument list of amici::initMatlabDiagnosisFields has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:17: warning: argument 'matlabStruct' from the argument list of amici::writeMatlabField0 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:17: warning: argument 'fieldName' from the argument list of amici::writeMatlabField0 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:17: warning: argument 'fieldData' from the argument list of amici::writeMatlabField0 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:20: warning: argument 'matlabStruct' from the argument list of amici::writeMatlabField1 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:20: warning: argument 'fieldName' from the argument list of amici::writeMatlabField1 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:20: warning: argument 'fieldData' from the argument list of amici::writeMatlabField1 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:20: warning: argument 'dim0' from the argument list of amici::writeMatlabField1 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'matlabStruct' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'fieldName' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'fieldData' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'dim0' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'dim1' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:23: warning: argument 'perm' from the argument list of amici::writeMatlabField2 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'matlabStruct' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'fieldName' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'fieldData' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'dim0' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'dim1' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'dim2' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:26: warning: argument 'perm' from the argument list of amici::writeMatlabField3 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'matlabStruct' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'fieldName' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'fieldData' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'dim0' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'dim1' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'dim2' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'dim3' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:29: warning: argument 'perm' from the argument list of amici::writeMatlabField4 has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:31: warning: argument 'matlabStruct' from the argument list of amici::initAndAttachArray has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:31: warning: argument 'fieldName' from the argument list of amici::initAndAttachArray has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:31: warning: argument 'dim' from the argument list of amici::initAndAttachArray has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:33: warning: argument 'fieldNames' from the argument list of amici::checkFieldNames has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:33: warning: argument 'fieldCount' from the argument list of amici::checkFieldNames has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:36: warning: argument 'input' from the argument list of amici::reorder has muliple @param documentation sections

/Users/travis/build/ICB-DCM/AMICI/include/amici/returndata_matlab.h:36: warning: argument 'order' from the argument list of amici::reorder has muliple @param documentation sections

travis_time:end:0aa64c02:start=1546855888018900000,finish=1546855983399458000,duration=95380558000
[0K[31;1mThe command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/run-doxygen.sh; fi" exited with 1.[0m
```

### PR DESCRIPTION
**Pull request by FFroehlich**

### CODE REVIEW

File: scripts/run-doxygen.sh [hunk 1]
```diff
@@ -71,6 +71,10 @@ cp ./refman.pdf ${AMICI_PATH}/AMICI_guide.pdf
 grep -v "warning: Unexpected html tag <img> found within <a href=...> context" ${DOXY_WARNING_FILE} > ${DOXY_WARNING_FILE}_tmp
 mv ${DOXY_WARNING_FILE}_tmp ${DOXY_WARNING_FILE}
 
+# suppress doxygen warnings about multiple param sections
+grep -v "has muliple @param documentation sections" ${DOXY_WARNING_FILE} > ${DOXY_WARNING_FILE}_tmp
```
Comment (dweindl) [inline scripts/run-doxygen.sh]:
```suggestion
grep -v "iple @param documentation sections" ${DOXY_WARNING_FILE} > ${DOXY_WARNING_FILE}_tmp
```

So we are still fine once the typo gets fixed?
